plugins {
    id 'stock.service'
}

dependencies {
    implementation libs.spring.boot.starter.webmvc
    implementation libs.spring.boot.starter.jdbc
    implementation libs.spring.boot.starter.flyway
    implementation libs.flyway.mysql
    runtimeOnly libs.mysql.connector.j

    testImplementation libs.spring.boot.testcontainers
    testImplementation libs.testcontainers.mysql
}
